spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/ecommerce?authSource=admin
      auto-index-creation: true

app:
  security:
    user:
      name: admin
      password: admin
